services:
  mysql:
    image: 'mysql:9.0.1'
    environment:
      - 'MYSQL_DATABASE=test'
      - 'MYSQL_USER=test'
      - 'MYSQL_PASSWORD=test'
      - 'MYSQL_ROOT_PASSWORD=test'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
